---
name: salsify-config
---
Dynamic\Salsify\Model\Fetcher:
  timeout: 2000

Dynamic\Salsify\Model\Mapper:
  skipUpToDate: true
  extensions:
    - Dynamic\Salsify\TypeHandler\RawHandler
    - Dynamic\Salsify\TypeHandler\BooleanHandler
    - Dynamic\Salsify\TypeHandler\LiteralHandler
    - Dynamic\Salsify\TypeHandler\Asset\FileHandler
    - Dynamic\Salsify\TypeHandler\Asset\ImageHandler
    - Dynamic\Salsify\TypeHandler\Relation\HasOneHandler
    - Dynamic\Salsify\TypeHandler\Relation\ManyHandler
    - Dynamic\Salsify\TypeHandler\Relation\SalsifyRelationHandler

SilverStripe\Assets\File:
  extensions:
    - Dynamic\Salsify\ORM\SalsifyIDExtension
    - Dynamic\Salsify\ORM\FileDataExtension

SilverStripe\Assets\Image:
  extensions:
    - Dynamic\Salsify\ORM\ImageDataExtension

SilverStripe\AssetAdmin\Forms\FileFormFactory:
  extensions:
    - Dynamic\Salsify\ORM\AssetFormFactoryExtension

SilverStripe\Admin\LeftAndMain:
  extensions:
    - Dynamic\Salsify\ORM\SalsifyFetchExtension

