---
name: salsify-config
---
Dynamic\Salsify\Model\Fetcher:
  timeout: 2000

Dynamic\Salsify\Model\Mapper:
  extensions:
    - Dynamic\Salsify\TypeHandler\RawHandler
    - Dynamic\Salsify\TypeHandler\Asset\FileHandler
    - Dynamic\Salsify\TypeHandler\Asset\ImageHandler
    - Dynamic\Salsify\TypeHandler\Relation\HasOneHandler
    - Dynamic\Salsify\TypeHandler\Relation\ManyHandler

SilverStripe\Assets\File:
  extensions:
    - Dyanmic\Salsify\ORM\SalsifyIDExtension

SilverStripe\AssetAdmin\Forms\FileFormFactory:
  extensions:
    - Dyanmic\Salsify\ORM\AssetFormFactoryExtension

SilverStripe\Admin\LeftAndMain:
  extensions:
    - Dyanmic\Salsify\ORM\SalsifyFetchExtension